#pragma once

#include <cstdint>

// Curated from SDK.json generated by MeatyEFTDumper V2 on 2026-09-15.
// Only fields and type indices used by this project are kept here.
namespace sdk
{
    // EFT.GamePlayerOwner
    namespace GamePlayerOwner
    {
        inline constexpr std::int32_t TypeIndex = 8621;
        inline constexpr std::uint64_t MyPlayer = 0x8; // static _myPlayer: EFT.Player
    }

    // EFT.GameWorld. ClientLocalGameWorld inherits these fields.
    namespace GameWorld
    {
        inline constexpr std::uint64_t Location = 0xE8; // <LocationId>k__BackingField: string
        inline constexpr std::uint64_t SynchronizableObjectLogicProcessor = 0x278; // <SynchronizableObjectLogicProcessor>k__BackingField: EFT.SynchronizableObjects.SynchronizableObjectLogicProcessor
    }

    // EFT.GameWorld fields read from a ClientLocalGameWorld instance.
    namespace ClientLocalGameWorld
    {
        inline constexpr std::uint64_t btrController = 0x28; // <BtrController>k__BackingField: EFT.Vehicle.BtrController
        inline constexpr std::uint64_t ExfiltrationController = 0x68; // <ExfiltrationController>k__BackingField: CommonAssets.Scripts.Game.ExfiltrationController
        inline constexpr std::uint64_t LootList = 0x1B0; // LootList: genericinst
        inline constexpr std::uint64_t RegisteredPlayers = 0x1D0; // RegisteredPlayers: genericinst
        inline constexpr std::uint64_t MainPlayer = 0x230; // MainPlayer: EFT.Player
        inline constexpr std::uint64_t Grenades = 0x2B8; // Grenades: genericinst
    }

    // CommonAssets.Scripts.Game.ExfiltrationController
    namespace ExfiltrationController
    {
        inline constexpr std::uint64_t ExfiltrationPoints = 0x20; // <ExfiltrationPoints>k__BackingField: EFT.Interactive.ExfiltrationPoint[]
        inline constexpr std::uint64_t ScavExfiltrationPoints = 0x28; // <ScavExfiltrationPoints>k__BackingField: EFT.Interactive.ScavExfiltrationPoint[]
        inline constexpr std::uint64_t MSecretExfiltrationPoints = 0x30; // <SecretExfiltrationPoints>k__BackingField: EFT.Interactive.SecretExfiltrations.SecretExfiltrationPoint[]
    }

    // EFT.Interactive.ExfiltrationPoint
    namespace ExfiltrationPoint
    {
        inline constexpr std::uint64_t Status = 0x58; // _status: EFT.Interactive.EExfiltrationStatus
        inline constexpr std::uint64_t Settings = 0x98; // Settings: EFT.Interactive.ExitTriggerSettings
        inline constexpr std::uint64_t EligibleEntryPoints = 0xC0; // EligibleEntryPoints: string[]
    }

    // EFT.Interactive.ExitTriggerSettings
    namespace ExitSettings
    {
        inline constexpr std::uint64_t Name = 0x18; // Name: string
    }

    // EFT.SynchronizableObjects.SynchronizableObject
    namespace SynchronizableObject
    {
        inline constexpr std::uint64_t Type = 0x68; // Type: EFT.SynchronizableObjects.SynchronizableObjectType
    }

    // EFT.SynchronizableObjects.SynchronizableObjectLogicProcessor
    namespace SynchronizableObjectLogicProcessor
    {
        inline constexpr std::uint64_t _activeSynchronizableObjects = 0x10; // _activeSynchronizableObjects: genericinst
    }

    // EFT.SynchronizableObjects.TripwireSynchronizableObject
    namespace TripwireSynchronizableObject
    {
        inline constexpr std::uint64_t _tripwireState = 0xE4; // _tripwireState: EFT.SynchronizableObjects.ETripwireState
        inline constexpr std::uint64_t FromPosition = 0x14C; // <FromPosition>k__BackingField: UnityEngine.Vector3
        inline constexpr std::uint64_t ToPosition = 0x158; // <ToPosition>k__BackingField: UnityEngine.Vector3
    }

    // EFT.Vehicle.BtrController
    namespace BtrController
    {
        inline constexpr std::uint64_t BtrView = 0x50; // <BtrView>k__BackingField: EFT.Vehicle.BTRView
    }

    // EFT.Vehicle.BTRView
    namespace BTRView
    {
        inline constexpr std::uint64_t turret = 0x60; // turret: EFT.Vehicle.BTRTurretView
        inline constexpr std::uint64_t previousPosition = 0xB4; // _previousPosition: UnityEngine.Vector3
    }

    // EFT.Vehicle.BTRTurretView
    namespace BTRTurretView
    {
        inline constexpr std::uint64_t attachedBot = 0x60; // _bot: genericinst
    }

    // EFT.Player
    namespace Player
    {
        inline constexpr std::uint64_t CharacterController = 0x40; // _characterController: ICharacterController
        inline constexpr std::uint64_t MovementContext = 0x60; // <MovementContext>k__BackingField: EFT.MovementContext
        inline constexpr std::uint64_t RibcageScaleCurrent = 0x150; // RibcageScaleCurrent: float
        inline constexpr std::uint64_t _playerBody = 0x1A0; // _playerBody: EFT.PlayerBody
        inline constexpr std::uint64_t ProceduralWeaponAnimation = 0x3C0; // <ProceduralWeaponAnimation>k__BackingField: EFT.Animations.ProceduralWeaponAnimation
        inline constexpr std::uint64_t GameWorld = 0x690; // <GameWorld>k__BackingField: EFT.GameWorld
        inline constexpr std::uint64_t Corpse = 0x728; // Corpse: EFT.Interactive.Corpse
        inline constexpr std::uint64_t Location = 0x928; // <Location>k__BackingField: string
        inline constexpr std::uint64_t Profile = 0x9C0; // <Profile>k__BackingField: EFT.Profile
        inline constexpr std::uint64_t _inventoryController = 0xA38; // _inventoryController: PlayerInventoryController
        inline constexpr std::uint64_t _handsController = 0xA40; // _handsController: AbstractHandsController
        inline constexpr std::uint64_t _playerLookRaycastTransform = 0xAD8; // _playerLookRaycastTransform: UnityEngine.Transform
        inline constexpr std::uint64_t PlayerBones = 0xB40; // <PlayerBones>k__BackingField: PlayerBones
    }

    // SimpleCharacterController
    namespace SimpleCharacterController
    {
        inline constexpr std::uint64_t Velocity = 0xF0; // _velocity: UnityEngine.Vector3
    }

    // FirearmController
    namespace FirearmController
    {
        inline constexpr std::uint64_t Firearms = 0xD0; // Firearms: EFT.Firearms
        inline constexpr std::uint64_t GunBaseTransform = 0x148; // GunBaseTransform: UnityEngine.Transform
        inline constexpr std::uint64_t Fireport = 0x150; // Fireport: EFT.BifacialTransform
    }

    // EFT.Firearms
    namespace Firearms
    {
        inline constexpr std::uint64_t Fireport = 0xD8; // _fireport: EFT.BifacialTransform
    }

    // EFT.BifacialTransform
    namespace BifacialTransform
    {
        inline constexpr std::uint64_t Original = 0x10; // Original: UnityEngine.Transform
    }

    // PlayerBones
    namespace PlayerBones
    {
        inline constexpr std::uint64_t WeaponRootThird = 0x40; // Weapon_Root_Third: UnityEngine.Transform
        inline constexpr std::uint64_t Ribcage = 0x148; // Ribcage: EFT.BifacialTransform
        inline constexpr std::uint64_t Fireport = 0x1D0; // Fireport: EFT.BifacialTransform
    }

    // ItemHandsController
    namespace ItemHandsController
    {
        inline constexpr std::uint64_t HandsHierarchy = 0x68; // _handsHierarchy: TransformLinks
        inline constexpr std::uint64_t Item = 0x70; // _item: EFT.InventoryLogic.Item
    }

    // TransformLinks
    namespace TransformLinks
    {
        inline constexpr std::uint64_t Self = 0x28; // Self: UnityEngine.Transform
    }

    // EFT.Animations.PlayerSpring
    namespace PlayerSpring
    {
        inline constexpr std::uint64_t Fireport = 0x88; // Fireport: UnityEngine.Transform
    }

    // EFT.NextObservedPlayer.ObservedPlayerView
    namespace ObservedPlayerView
    {
        inline constexpr std::uint64_t ObservedPlayerController = 0x28; // <ObservedPlayerController>k__BackingField: EFT.NextObservedPlayer.ObservedPlayerController
        inline constexpr std::uint64_t Voice = 0x40; // <Voice>k__BackingField: string
        inline constexpr std::uint64_t Side = 0xB4; // <Side>k__BackingField: EFT.EPlayerSide
        inline constexpr std::uint64_t IsAI = 0xC0; // <IsAI>k__BackingField: bool
        inline constexpr std::uint64_t PlayerBody = 0xF8; // <PlayerBody>k__BackingField: EFT.PlayerBody
    }

    // EFT.NextObservedPlayer.ObservedPlayerController
    namespace ObservedPlayerController
    {
        inline constexpr std::uint64_t InventoryController = 0x10; // <InventoryController>k__BackingField: EFT.NextObservedPlayer.ObservedPlayerInventoryController
        inline constexpr std::uint64_t MovementController = 0xF0; // <MovementController>k__BackingField: EFT.NextObservedPlayer.ObservedPlayerMovementController
        inline constexpr std::uint64_t HealthController = 0x100; // <HealthController>k__BackingField: ObservedPlayerHealthController
        inline constexpr std::uint64_t HandsController = 0x140; // <HandsController>k__BackingField: EFT.NextObservedPlayer.ObservedPlayerHandsController
    }

    // EFT.NextObservedPlayer.ObservedPlayerMovementController
    namespace ObservedMovementController
    {
        inline constexpr std::uint64_t ObservedPlayerStateContext = 0xB0; // <ObservedPlayerStateContext>k__BackingField: EFT.NextObservedPlayer.ObservedPlayerStateContext
    }

    // EFT.NextObservedPlayer.ObservedPlayerStateContext
    namespace ObservedPlayerStateContext
    {
        inline constexpr std::uint64_t Rotation = 0x28; // <Rotation>k__BackingField: UnityEngine.Vector2
        inline constexpr std::uint64_t Velocity = 0xF8; // _velocity: UnityEngine.Vector3
    }

    // EFT.NextObservedPlayer.ObservedPlayerHandsController
    namespace ObservedPlayerHands
    {
        inline constexpr std::uint64_t Item = 0x58; // _item: EFT.InventoryLogic.Item
    }

    // ObservedPlayerHealthController
    namespace ObservedHealthController
    {
        inline constexpr std::uint64_t HealthStatus = 0x10; // HealthStatus: ETagStatus
        inline constexpr std::uint64_t PlayerCorpse = 0x48; // _playerCorpse: EFT.Interactive.ObservedCorpse
    }

    // EFT.InventoryLogic.InventoryController
    namespace InventoryController
    {
        inline constexpr std::uint64_t Inventory = 0x100; // <Inventory>k__BackingField: EFT.InventoryLogic.Inventory
    }

    // EFT.InventoryLogic.Inventory
    namespace Inventory
    {
        inline constexpr std::uint64_t Equipment = 0x18; // Equipment: EFT.InventoryLogic.InventoryEquipment
    }

    // EFT.InventoryLogic.InventoryEquipment
    namespace InventoryEquipment
    {
        inline constexpr std::uint64_t _cachedSlots = 0x90; // _cachedSlots: EFT.InventoryLogic.Slot[]
    }

    // EFT.InventoryLogic.Slot
    namespace Slot
    {
        inline constexpr std::uint64_t ContainedItem = 0x48; // <ContainedItem>k__BackingField: EFT.InventoryLogic.Item
        inline constexpr std::uint64_t ID = 0x58; // <ID>k__BackingField: string
    }

    // EFT.InventoryLogic.Weapon
    namespace Weapon
    {
        inline constexpr std::uint64_t Chambers = 0xB0; // <Chambers>k__BackingField: EFT.InventoryLogic.Slot[]
        inline constexpr std::uint64_t MagazineSlotCache = 0xC8; // _magSlotCache: EFT.InventoryLogic.Slot
    }

    // EFT.InventoryLogic.Magazine
    namespace Magazine
    {
        inline constexpr std::uint64_t Cartridges = 0xA8; // <Cartridges>k__BackingField: EFT.InventoryLogic.StackSlot
    }

    // EFT.InventoryLogic.Item
    namespace Item
    {
        inline constexpr std::uint64_t StackObjectsCount = 0x24; // StackObjectsCount: int32_t
        inline constexpr std::uint64_t Version = 0x28; // Version: int32_t
        inline constexpr std::uint64_t Template = 0x60; // Template: EFT.InventoryLogic.ItemTemplate
    }

    // EFT.InventoryLogic.StackSlot
    namespace StackSlot
    {
        inline constexpr std::uint64_t MaxCount = 0x10; // MaxCount: int32_t
        inline constexpr std::uint64_t items = 0x18; // _items: genericinst
    }

    // EFT.InventoryLogic.BarterOther
    namespace BarterOtherOffsets
    {
        inline constexpr std::uint64_t Dogtag = 0x80; // Dogtag: EFT.InventoryLogic.DogtagComponent
    }

    // EFT.InventoryLogic.DogtagComponent
    namespace DogtagComponent
    {
        inline constexpr std::uint64_t AccountId = 0x20; // AccountId: string
        inline constexpr std::uint64_t ProfileId = 0x28; // ProfileId: string
        inline constexpr std::uint64_t Nickname = 0x30; // Nickname: string
        inline constexpr std::uint64_t Level = 0x3C; // Level: int32_t
        inline constexpr std::uint64_t KillerAccountId = 0x50; // KillerAccountId: string
        inline constexpr std::uint64_t KillerProfileId = 0x58; // KillerProfileId: string
        inline constexpr std::uint64_t KillerName = 0x60; // KillerName: string
    }

    // EFT.Profile
    namespace Profile
    {
        inline constexpr std::uint64_t Info = 0x48; // Info: EFT.ProfileInfo
        inline constexpr std::uint64_t QuestsData = 0x98; // QuestsData: genericinst
        inline constexpr std::uint64_t WishlistManager = 0x130; // WishlistManager: EFT.WishlistManager
    }

    // EFT.WishlistManager
    namespace WishlistManager
    {
        inline constexpr std::uint64_t _wishlistItems = 0x30; // _wishlistItems: genericinst
    }

    // EFT.Quests.QuestStatusData
    namespace QuestsData
    {
        inline constexpr std::uint64_t Id = 0x10; // Id: string
        inline constexpr std::uint64_t Status = 0x1C; // Status: EFT.Quests.EQuestStatus
        inline constexpr std::uint64_t CompletedConditions = 0x28; // CompletedConditions: genericinst
    }

    // EFT.ProfileInfo
    namespace PlayerInfo
    {
        inline constexpr std::uint64_t Side = 0x48; // <Side>k__BackingField: EFT.EPlayerSide
    }

    // EFT.MovementContext
    namespace MovementContext
    {
        inline constexpr std::uint64_t _rotation = 0xC0; // _rotation: UnityEngine.Vector2
    }

    // EFT.Animations.ProceduralWeaponAnimation
    namespace ProceduralWeaponAnimation
    {
        inline constexpr std::uint64_t HandsContainer = 0x38; // HandsContainer: EFT.Animations.PlayerSpring
        inline constexpr std::uint64_t _isAiming = 0x16D; // _isAiming: bool
        inline constexpr std::uint64_t _optics = 0x1C8; // _optics: genericinst
    }

    // SightNBone
    namespace SightNBone
    {
        inline constexpr std::uint64_t Mod = 0x10; // Mod: EFT.InventoryLogic.SightComponent
        inline constexpr std::uint64_t Bone = 0x18; // Bone: UnityEngine.Transform
    }

    // EFT.InventoryLogic.SightComponent
    namespace SightComponent
    {
        inline constexpr std::uint64_t _template = 0x20; // _template: EFT.InventoryLogic.ISightComponentTemplate
        inline constexpr std::uint64_t ScopeSelectedModes = 0x30; // ScopesSelectedModes: int32_t[]
        inline constexpr std::uint64_t SelectedScope = 0x38; // SelectedScope: int32_t
        inline constexpr std::uint64_t ScopeZoomValue = 0x3C; // ScopeZoomValue: float
    }

    // EFT.InventoryLogic.SightModTemplate
    namespace SightInterface
    {
        inline constexpr std::uint64_t Zooms = 0x1B8; // Zooms: float[][]
    }

    // EFT.CameraControl.CameraManager
    namespace CameraManager
    {
        inline constexpr std::uint64_t Instance = 0x0; // static instance: EFT.CameraControl.CameraManager
        inline constexpr std::uint64_t OpticCameraManager = 0x10; // <OpticCameraManager>k__BackingField: EFT.CameraControl.OpticCameraManager
        inline constexpr std::uint64_t Camera = 0x70; // <Camera>k__BackingField: UnityEngine.Camera
    }

    // EFT.CameraControl.OpticCameraManager
    namespace OpticCameraManager
    {
        inline constexpr std::uint64_t Camera = 0x70; // <Camera>k__BackingField: UnityEngine.Camera
        inline constexpr std::uint64_t CurrentOpticSight = 0x78; // <CurrentOpticSight>k__BackingField: EFT.CameraControl.OpticSight
    }

    // EFT.CameraControl.OpticSight
    namespace OpticSight
    {
        inline constexpr std::uint64_t LensRenderer = 0x30; // LensRenderer: UnityEngine.Renderer
        inline constexpr std::uint64_t ScopeTransform = 0x40; // ScopeTransform: UnityEngine.Transform
    }

    // EFT.Interactive.LootItem
    namespace InteractiveLootItem
    {
        inline constexpr std::uint64_t Item = 0xF0; // _item: EFT.InventoryLogic.Item
    }

    // EFT.InventoryLogic.CompoundItem
    namespace LootItemMod
    {
        inline constexpr std::uint64_t Slots = 0x80; // <Slots>k__BackingField: EFT.InventoryLogic.Slot[]
    }

    // EFT.Interactive.LootableContainer
    namespace LootableContainer
    {
        inline constexpr std::uint64_t InteractingPlayer = 0x160; // inherited WorldInteractiveObject.<InteractingPlayer>k__BackingField: EFT.IPlayer
        inline constexpr std::uint64_t ItemOwner = 0x178; // ItemOwner: EFT.InventoryLogic.ItemController
    }

    // EFT.InventoryLogic.ItemController
    namespace LootableContainerItemOwner
    {
        inline constexpr std::uint64_t RootItem = 0xD0; // <RootItem>k__BackingField: EFT.InventoryLogic.Item
    }

    // EFT.InventoryLogic.Item compatibility name retained for existing loot readers.
    namespace LootItem
    {
        inline constexpr std::uint64_t Version = Item::Version;
        inline constexpr std::uint64_t Template = Item::Template;
    }

    // EFT.InventoryLogic.ItemTemplate
    namespace ItemTemplate
    {
        inline constexpr std::uint64_t ShortName = 0x18; // ShortName: string
        inline constexpr std::uint64_t QuestItem = 0x34; // QuestItem: bool
        inline constexpr std::uint64_t _id = 0xE0; // <_id>k__BackingField: EFT.MongoID
    }

    // EFT.InventoryLogic.ModTemplate
    namespace ModTemplate
    {
        inline constexpr std::uint64_t Velocity = 0x188; // Velocity: float
    }

    // EFT.InventoryLogic.AmmoTemplate. Misspellings in comments are the dumped field names.
    namespace AmmoTemplate
    {
        inline constexpr std::uint64_t InitialSpeed = 0x1A4; // InitialSpeed: float
        inline constexpr std::uint64_t BallisticCoefficient = 0x1B8; // BallisticCoeficient: float
        inline constexpr std::uint64_t BulletMassGrams = 0x25C; // BulletMassGram: float
        inline constexpr std::uint64_t BulletDiameterMillimeters = 0x260; // BulletDiameterMilimeters: float
    }

    // EFT.InventoryLogic.WeaponTemplate
    namespace WeaponTemplate
    {
        inline constexpr std::uint64_t Velocity = 0x25C; // Velocity: float
    }

    // Throwable
    namespace Throwable
    {
        inline constexpr std::uint64_t _isDestroyed = 0x4D; // _isDestroyed: bool
    }

    // EFT.Hideout.HideoutController
    namespace HideoutController
    {
        inline constexpr std::uint64_t Areas = 0x80; // _areas: genericinst
    }

    // EFT.Hideout.HideoutArea
    namespace HideoutArea
    {
        inline constexpr std::uint64_t Levels = 0x48; // _areaLevels: EFT.Hideout.HideoutAreaLevel[]
        inline constexpr std::uint64_t Data = 0x70; // _data: EFT.Hideout.AreaData
    }

    // EFT.Hideout.AreaData
    namespace HideoutAreaData
    {
        inline constexpr std::uint64_t CurrentLevel = 0xA8; // _currentLevel: int32_t
        inline constexpr std::uint64_t Status = 0xC8; // _status: EFT.Hideout.EAreaStatus
    }

    // EFT.Hideout.HideoutAreaLevel
    namespace HideoutAreaLevel
    {
        inline constexpr std::uint64_t Stage = 0xA0; // _stage: EFT.Hideout.Stage
    }

    // EFT.Hideout.Stage
    namespace HideoutStage
    {
        inline constexpr std::uint64_t Requirements = 0x18; // Requirements: EFT.Hideout.RelatedRequirements
    }

    // EFT.Hideout.RelatedRequirements
    namespace HideoutRelatedRequirements
    {
        inline constexpr std::uint64_t Data = 0x10; // Data: genericinst
    }

    // EFT.Hideout.Requirement
    namespace HideoutRequirement
    {
        inline constexpr std::uint64_t Fulfilled = 0x18; // <Fulfilled>k__BackingField: bool
    }

    // EFT.Hideout.ItemRequirement (also inherited by ToolRequirement)
    namespace HideoutItemRequirement
    {
        inline constexpr std::uint64_t TemplateId = 0x48; // <TemplateId>k__BackingField: string
        inline constexpr std::uint64_t UserItemsCount = 0x54; // <UserItemsCount>k__BackingField: int32_t
        inline constexpr std::uint64_t RequiredCount = 0x5C; // _baseCount: int32_t
    }

    // EFT.Hideout.AreaRequirement
    namespace HideoutAreaRequirement
    {
        inline constexpr std::uint64_t AreaType = 0x38; // AreaType: EFT.EAreaType
        inline constexpr std::uint64_t RequiredLevel = 0x3C; // RequiredLevel: int32_t
    }

    // EFT.Hideout.SkillRequirement
    namespace HideoutSkillRequirement
    {
        inline constexpr std::uint64_t SkillName = 0x38; // SkillName: string
        inline constexpr std::uint64_t SkillLevel = 0x40; // SkillLevel: int32_t
    }

    // EFT.Hideout.TraderUnlockRequirement
    namespace HideoutTraderUnlockRequirement
    {
        inline constexpr std::uint64_t TraderId = 0x40; // TraderId: string
    }

    // EFT.Hideout.TraderLoyaltyRequirement
    namespace HideoutTraderLoyaltyRequirement
    {
        inline constexpr std::uint64_t LoyaltyLevel = 0x40; // LoyaltyLevel: int32_t
        inline constexpr std::uint64_t TraderId = 0x48; // TraderId: string
    }

    // EFT.Hideout.HideoutAreaQTEOverlay
    namespace HideoutAreaQTEOverlay
    {
        inline constexpr std::int32_t TypeIndex = 9689;
        inline constexpr std::uint64_t QteController = 0x0; // static QteController: EFT.Hideout.QTEController
    }

    // EFT.Hideout.QTEController
    namespace QTEController
    {
        inline constexpr std::int32_t TypeIndex = 9728;
        inline constexpr std::uint64_t SpawnedQtes = 0x90; // _spawnedQtes: genericinst
    }

    // EFT.Hideout.ShrinkingCircleQTE
    namespace ShrinkingCircleQTE
    {
        inline constexpr std::int32_t TypeIndex = 9740;
        inline constexpr std::uint64_t Speed = 0x20; // _speed: float
        inline constexpr std::uint64_t SuccessRange = 0x24; // _successRange: UnityEngine.Vector2
        inline constexpr std::uint64_t MinScale = 0x2C; // _minScale: float
        inline constexpr std::uint64_t TargetInput = 0x30; // _targetInput: UnityEngine.KeyCode
        inline constexpr std::uint64_t DynamicCircleImage = 0x38; // _dynamicCircleImage: UnityEngine.UI.Image
        inline constexpr std::uint64_t DynamicCircleInnerBorder = 0x40; // _dynamicCircleInnerBorder: UnityEngine.Transform
        inline constexpr std::uint64_t SuccessStartScale = 0x90; // _successStartScale: double
        inline constexpr std::uint64_t SuccessEndScale = 0x98; // _successEndScale: double
        inline constexpr std::uint64_t IsSuccess = 0xA0; // _isSuccess: bool
    }
}
