#pragma once

#include <array>
#include <string_view>

namespace ExfilNames
{
    struct ExfilNameTranslation
    {
        std::string_view memoryName;
        std::string_view displayName;
    };

    inline constexpr std::array translations =
    {
        ExfilNameTranslation{ "Adm Basement", "Admin Basement" },
        ExfilNameTranslation{ "Alpinist", "Cliff Descent" },
        ExfilNameTranslation{ "Alpinist_light", "Mountain Pass" },
        ExfilNameTranslation{ "Beyond Fuel Tank", "Passage Between Rocks" },
        ExfilNameTranslation{ "Camera Bunker Door", "Camera Bunker Door" },
        ExfilNameTranslation{ "CCP Temporary", "CCP Temporary" },
        ExfilNameTranslation{ "Cellars", "Cellars" },
        ExfilNameTranslation{ "Coastal_South_Road", "Southern Road" },
        ExfilNameTranslation{ "Dead Man's Place", "Dead Man's Place" },
        ExfilNameTranslation{ "E1", "Stylobate Building Elevator" },
        ExfilNameTranslation{ "E2", "Sewer River" },
        ExfilNameTranslation{ "E3", "Damaged House" },
        ExfilNameTranslation{ "E4", "Crash Site" },
        ExfilNameTranslation{ "E5", "Collapsed Crane" },
        ExfilNameTranslation{ "E6", "Scav Checkpoint" },
        ExfilNameTranslation{ "E7", "Expo Checkpoint" },
        ExfilNameTranslation{ "E7_car", "Taxi V-Ex" },
        ExfilNameTranslation{ "E8_yard", "Courtyard" },
        ExfilNameTranslation{ "E9_sniper", "Klimov Street (Flare)" },
        ExfilNameTranslation{ "East Gate", "Scav Bunker" },
        ExfilNameTranslation{ "ex_customs_coop_boiler", "Boiler Room Basement (Co-op)" },
        ExfilNameTranslation{ "ex_customs_pmc_auto", "Dorms V-Ex" },
        ExfilNameTranslation{ "ex_customs_pmc_crossroads", "Crossroads" },
        ExfilNameTranslation{ "ex_customs_pmc_flare", "Railroad Passage (Flare)" },
        ExfilNameTranslation{ "ex_customs_pmc_gasstation", "Old Gas Station" },
        ExfilNameTranslation{ "ex_customs_pmc_rail_milbase", "Railroad to Milbase" },
        ExfilNameTranslation{ "ex_customs_pmc_trailerpark", "Trailer Park" },
        ExfilNameTranslation{ "ex_customs_pmc_zb1011", "ZB-1011" },
        ExfilNameTranslation{ "ex_customs_pmc_zb1013", "ZB-1013" },
        ExfilNameTranslation{ "ex_customs_scav_admin", "Administration Gate" },
        ExfilNameTranslation{ "ex_customs_scav_gasstation", "Old Gas Station Gate" },
        ExfilNameTranslation{ "ex_customs_scav_medgate", "Gate Near Medblock" },
        ExfilNameTranslation{ "ex_customs_scav_milbase_cp", "Scav Checkpoint" },
        ExfilNameTranslation{ "ex_customs_scav_rail_milbase", "Railroad to Military Base" },
        ExfilNameTranslation{ "ex_customs_scav_rail_port", "Railroad to Port" },
        ExfilNameTranslation{ "ex_customs_scav_rail_tarkov", "Railroad to Tarkov" },
        ExfilNameTranslation{ "ex_customs_scav_trailerpark", "Trailer Park" },
        ExfilNameTranslation{ "ex_customs_scav_zb1011", "ZB-1011" },
        ExfilNameTranslation{ "ex_customs_secret_voron_boat", "Smugglers' Boat" },
        ExfilNameTranslation{ "ex_customs_secret_voron_bunker", "Smugglers' Bunker (ZB-1012)" },
        ExfilNameTranslation{ "ex_interchange_coop_basement", "Scav Camp (Co-Op)" },
        ExfilNameTranslation{ "ex_interchange_pmc_auto", "Power Station V-Ex" },
        ExfilNameTranslation{ "ex_interchange_pmc_emercom", "Emercom Checkpoint" },
        ExfilNameTranslation{ "ex_interchange_pmc_railway", "Railway Exfil" },
        ExfilNameTranslation{ "ex_interchange_pmc_saferoom", "Saferoom Exfil" },
        ExfilNameTranslation{ "ex_interchange_pmc_sniper", "Path to River (Flare)" },
        ExfilNameTranslation{ "ex_interchange_scav_emercom", "Emercom Checkpoint" },
        ExfilNameTranslation{ "ex_interchange_scav_railway", "Railway Exfil" },
        ExfilNameTranslation{ "EXFIL_Bunker", "Bunker Hermetic Door" },
        ExfilNameTranslation{ "EXFIL_Bunker_D2", "D-2" },
        ExfilNameTranslation{ "EXFIL_ScavCooperation", "Scav Lands (Co-Op)" },
        ExfilNameTranslation{ "EXFIL_Train", "Armored Train" },
        ExfilNameTranslation{ "EXFIL_vent", "Sewer Manhole" },
        ExfilNameTranslation{ "Exit_E10_coop", "Pinewood Basement (Co-Op)" },
        ExfilNameTranslation{ "Exit1", "Hole in the Wall by the Mountains" },
        ExfilNameTranslation{ "Exit2", "Heating Pipe" },
        ExfilNameTranslation{ "Exit3", "Depot Hermetic Door" },
        ExfilNameTranslation{ "Exit4", "Checkpoint Fence" },
        ExfilNameTranslation{ "Factory Gate", "Friendship Bridge (Co-Op)" },
        ExfilNameTranslation{ "Factory Shacks", "Factory Shacks" },
        ExfilNameTranslation{ "factory_secret_ark", "Smugglers' Passage" },
        ExfilNameTranslation{ "Gate 0", "Gate 0" },
        ExfilNameTranslation{ "Gate 2", "Gate 2" },
        ExfilNameTranslation{ "Gate 3", "Gate 3" },
        ExfilNameTranslation{ "Gate m", "Med Tent Gate" },
        ExfilNameTranslation{ "Gate_o", "Courtyard Gate" },
        ExfilNameTranslation{ "groundzero_secret_adaptation", "Tartowers Sales Office" },
        ExfilNameTranslation{ "Heli", "Helicopter" },
        ExfilNameTranslation{ "Hole Exfill", "Hole in the Fence" },
        ExfilNameTranslation{ "lab_Elevator_Cargo", "Cargo Elevator" },
        ExfilNameTranslation{ "lab_Elevator_Main", "Main Elevator" },
        ExfilNameTranslation{ "lab_Elevator_Med", "Medical Block Elevator" },
        ExfilNameTranslation{ "lab_Hangar_Gate", "Hangar Gate" },
        ExfilNameTranslation{ "lab_Parking_Gate", "Parking Gate" },
        ExfilNameTranslation{ "lab_Under_Storage_Collector", "Sewage Conduit" },
        ExfilNameTranslation{ "lab_Vent", "Ventilation Shaft" },
        ExfilNameTranslation{ "labir_exit", "The Way Up" },
        ExfilNameTranslation{ "labyrinth_secret_tagilla_key", "Ariadne's Path" },
        ExfilNameTranslation{ "Lighthouse", "Lighthouse" },
        ExfilNameTranslation{ "Lighthouse_pass", "Path to Lighthouse" },
        ExfilNameTranslation{ "lighthouse_secret_minefield", "Passage by the Lake" },
        ExfilNameTranslation{ "Mountain Stash", "Mountain Stash" },
        ExfilNameTranslation{ "Nakatani_stairs_free_exit", "Nakatani Basement Stairs" },
        ExfilNameTranslation{ "Nothern_Checkpoint", "Northern Checkpoint" },
        ExfilNameTranslation{ "Office Window", "Office Window" },
        ExfilNameTranslation{ "Old Road Gate", "Old Road Gate" },
        ExfilNameTranslation{ "Old Station", "Old Railway Depot" },
        ExfilNameTranslation{ "Outskirts", "Outskirts" },
        ExfilNameTranslation{ "Pier Boat", "Pier Boat" },
        ExfilNameTranslation{ "RedRebel_alp", "Climber's Trail" },
        ExfilNameTranslation{ "reserve_secret_minefield", "Exit to Woods" },
        ExfilNameTranslation{ "Road to Customs", "Road to Customs" },
        ExfilNameTranslation{ "Road_at_railbridge", "Railway Bridge" },
        ExfilNameTranslation{ "Rock Passage", "Rock Passage" },
        ExfilNameTranslation{ "RUAF Gate", "RUAF Gate" },
        ExfilNameTranslation{ "RUAF Roadblock", "RUAF Roadblock" },
        ExfilNameTranslation{ "RUAF Roadblock_scav", "RUAF Roadblock" },
        ExfilNameTranslation{ "Ruined House Fence", "Ruined House Fence" },
        ExfilNameTranslation{ "RWing Gym Entrance", "East Wing Gym Entrance" },
        ExfilNameTranslation{ "Sandbox_VExit", "Police Cordon V-Ex" },
        ExfilNameTranslation{ "Scav House", "Scav House" },
        ExfilNameTranslation{ "Scav Road to Customs", "Road to Customs" },
        ExfilNameTranslation{ "Scav_Coastal_South", "Southern Road Landslide" },
        ExfilNameTranslation{ "Scav_coop_exit", "Scav Checkpoint (Co-op)" },
        ExfilNameTranslation{ "scav_e2", "Entrance to Catacombs" },
        ExfilNameTranslation{ "scav_e3", "Ventilation Shaft" },
        ExfilNameTranslation{ "scav_e4", "Sewer Manhole" },
        ExfilNameTranslation{ "scav_e5", "Near Kamchatskaya Arch" },
        ExfilNameTranslation{ "scav_e6", "Basement Entrance" },
        ExfilNameTranslation{ "scav_e7", "Cardinal Apartment Complex Parking" },
        ExfilNameTranslation{ "scav_e8", "Klimov Shopping Mall Exfil" },
        ExfilNameTranslation{ "Scav_Hideout_at_the_grotto", "Scav Hideout at the Grotto" },
        ExfilNameTranslation{ "Scav_Industrial_zone", "Industrial Zone Gates" },
        ExfilNameTranslation{ "Scav_Underboat_Hideout", "Hideout Under the Landing Stage" },
        ExfilNameTranslation{ "shoreline_secret_heartbeat", "Mountain Bunker" },
        ExfilNameTranslation{ "Shorl_free", "Path to Shoreline" },
        ExfilNameTranslation{ "Shorl_free_scav", "Path to Shoreline" },
        ExfilNameTranslation{ "Shorl_V-Ex", "Road to North V-Ex" },
        ExfilNameTranslation{ "Smugglers_Trail_coop", "Smugglers' Path (Co-op)" },
        ExfilNameTranslation{ "Sniper Roadblock", "Sniper Roadblock" },
        ExfilNameTranslation{ "Sniper_exit", "Mira Ave (Flare)" },
        ExfilNameTranslation{ "South V-Ex", "Bridge V-Ex" },
        ExfilNameTranslation{ "streets_secret_onyx", "Smugglers' Basement" },
        ExfilNameTranslation{ "Svetliy Dead End", "Svetliy Dead End" },
        ExfilNameTranslation{ "The Boat", "Boat" },
        ExfilNameTranslation{ "Tunnel", "Tunnel" },
        ExfilNameTranslation{ "tunnel_shared", "Side Tunnel (Co-Op)" },
        ExfilNameTranslation{ "UN Roadblock", "UN Roadblock" },
        ExfilNameTranslation{ "un-sec", "Northern UN Roadblock" },
        ExfilNameTranslation{ "Unity_free_exit", "Emercom Checkpoint" },
        ExfilNameTranslation{ "Warehouse 4", "Warehouse 4" },
        ExfilNameTranslation{ "West Border", "Eastern Rocks" },
        ExfilNameTranslation{ "wood_sniper_exit", "Power Line Passage (Flare)" },
        ExfilNameTranslation{ "woods_secret_minefield", "Railway Bridge to Tarkov" },
        ExfilNameTranslation{ "Wrecked Road", "Ruined Road" },
        ExfilNameTranslation{ "ZB-014", "ZB-014" },
        ExfilNameTranslation{ "ZB-016", "ZB-016" },
    };

    [[nodiscard]] constexpr std::string_view ToDisplayName(const std::string_view memoryName) noexcept
    {
        for (const ExfilNameTranslation& translation : translations)
        {
            if (translation.memoryName == memoryName)
                return translation.displayName;
        }

        return memoryName;
    }

    static_assert(ToDisplayName("Gate m") == "Med Tent Gate");
    static_assert(ToDisplayName("Unknown future exfil") == "Unknown future exfil");
}
