#pragma once

#include <cstdint>

// Generated by MeatyEFTDumper V2 for Unity 2022.3.43f2.
// Contains only scan-resolved or live-validated values.
// A zero means that field did not pass live validation this run.
// RVAs must be added to the module named in each section.
namespace UnityOffsets
{
    inline constexpr const char* UnityVersion = "2022.3.43f2";

    // UnityPlayer.dll RVAs
    inline constexpr std::uint64_t GameObjectManager = 0x1A233A0;
    inline constexpr std::uint64_t AllCamera = 0x19F3080;

    // GameAssembly.dll RVAs
    inline constexpr std::uint64_t CameraManagerBSS = 0x6E2D7E8;
    // Direct GamePlayerOwner path anchor (TypeInfoTable global RVA)
    inline constexpr std::uint64_t GameWorld = 0x70FD1A8;

    // AllCameras native container
    inline constexpr std::uint64_t AllCameras_ItemsOffset = 0x0;
    inline constexpr std::uint64_t AllCameras_CountOffset = 0x10;
    inline constexpr std::uint64_t AllCameras_CapacityOffset = 0x18;

    // GameObjectManager and linked-list layout
    inline constexpr std::uint64_t GameObjectManager_LastActiveNodeOffset = 0x20;
    inline constexpr std::uint64_t GameObjectManager_ActiveNodesOffset = 0x28;
    inline constexpr std::uint64_t LinkedList_PreviousOffset = 0x8;
    inline constexpr std::uint64_t LinkedList_NextOffset = 0x0;
    inline constexpr std::uint64_t LinkedList_ThisObjectOffset = 0x10;

    // Native GameObject and Component layout
    inline constexpr std::uint64_t GameObject_ObjectClassOffset = 0x0;
    inline constexpr std::uint64_t GameObject_ComponentsOffset = 0x58;
    inline constexpr std::uint64_t GameObject_NameOffset = 0x88;
    inline constexpr std::uint64_t Component_ObjectClassOffset = 0x50;
    inline constexpr std::uint64_t Component_GameObjectOffset = 0x88;
    inline constexpr std::uint64_t ComponentArray_SizeOffset = 0x10;
    inline constexpr std::uint64_t ComponentArray_CapacityOffset = 0x18;
    inline constexpr std::uint64_t ComponentArray_EntryComponentOffset = 0x10;
    inline constexpr std::uint64_t ComponentArray_EntryStride = 0x20;

    // Native Transform layout, resolved from live Transform components
    inline constexpr std::uint64_t ManagedObject_NativePointerOffset = 0x10;
    inline constexpr std::uint64_t ObjectClass_TransformInternalOffset = 0x10;
    inline constexpr std::uint64_t TransformInternal_TransformAccessOffset = 0x70;
    inline constexpr std::uint64_t TransformAccess_HierarchyOffset = 0x70;
    inline constexpr std::uint64_t TransformAccess_IndexOffset = 0x78;
    inline constexpr std::uint64_t Hierarchy_VerticesOffset = 0x68;
    inline constexpr std::uint64_t Hierarchy_IndicesOffset = 0x40;

    inline constexpr std::uint64_t TransformChain[] =
    {
        ManagedObject_NativePointerOffset,
        Component_GameObjectOffset,
        GameObject_ComponentsOffset,
        ComponentArray_EntryComponentOffset,
        Component_ObjectClassOffset,
        ObjectClass_TransformInternalOffset
    };

    // Native Camera members
    inline constexpr std::uint64_t Camera_ViewMatrixOffset = 0x128;
    inline constexpr std::uint64_t Camera_FOVOffset = 0x1A8;
    inline constexpr std::uint64_t Camera_AspectRatioOffset = 0x518;
}
